src/Entity/Horario.php
<?php

namespace App\Entity;

use App\Repository\HorarioRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HorarioRepository::class)]
class Horario
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $Dia = null;

    #[ORM\Column(length: 40)]
    private ?string $Horario_inicio = null;

    #[ORM\Column(length: 40)]
    private ?string $Horario_fin = null;

    #[ORM\Column(length: 255)]
    private ?string $Cant_modulos = null;

    #[ORM\ManyToOne(inversedBy: 'horarios')]
    private ?Curso $Curso = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDia(): ?string
    {
        return $this->Dia;
    }

    public function setDia(string $Dia): static
    {
        $this->Dia = $Dia;

        return $this;
    }

    public function getHorarioInicio(): ?string
    {
        return $this->Horario_inicio;
    }

    public function setHorarioInicio(string $Horario_inicio): static
    {
        $this->Horario_inicio = $Horario_inicio;

        return $this;
    }

    public function getHorarioFin(): ?string
    {
        return $this->Horario_fin;
    }

    public function setHorarioFin(string $Horario_fin): static
    {
        $this->Horario_fin = $Horario_fin;

        return $this;
    }

    public function getCantModulos(): ?string
    {
        return $this->Cant_modulos;
    }

    public function setCantModulos(string $Cant_modulos): static
    {
        $this->Cant_modulos = $Cant_modulos;

        return $this;
    }

    public function getCurso(): ?Asignatura
    {
        return $this->Curso;
    }

    public function setCurso(?Curso $Curso): static
    {
        $this->Curso = $Curso;

        return $this;
    }
}

src/Controller/VistascursadaController.php
<?php

namespace App\Controller;

use App\Entity\Nota;
use App\Form\NotaType;
use App\Repository\NotaRepository;
use App\Entity\Asignatura;
use App\Form\AsignaturaType;
use App\Repository\AsignaturaRepository;
use App\Entity\Tecnicatura;
use App\Form\TecnicaturaType;
use App\Repository\TecnicaturaRepository;
use App\Entity\Comision;
use App\Form\ComisionType;
use App\Repository\ComisionRepository;
use App\Entity\Cursada;
use App\Form\CursadaType;
use App\Repository\CursadaRepository;
use App\Entity\Curso;
use App\Form\CursoType;
use App\Repository\CursoRepository;
use App\Entity\CursadaDocente;
use App\Form\CursadaDocenteType;
use App\Repository\CursadaDocenteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class VistascursadaController extends AbstractController
{
    #[Route('/vistascursada', name: 'app_vistascursada')]
    public function index(
        CursadaDocenteRepository $cursadaDocenteRepository, 
        CursoRepository $cursoRepository, 
        CursadaRepository $cursadaRepository, 
        ComisionRepository $comisionRepository, 
        TecnicaturaRepository $tecnicaturaRepository, 
        AsignaturaRepository $asignaturaRepository, 
        Request $request
    ): Response {
        // Recuperar `tecId`, `comId`, `cursoId` de la sesión
        $session = $request->getSession();
        $tecId = $session->get('tecId', null);
        $comId = $session->get('comId', null);
        $cursoId = $session->get('cursoId', null);
    

        // Obtener el ciclo lectivo de la solicitud o usar el año actual
        $cicloLectivo = $request->query->get('cicloLectivo', date('Y'));


        // Filtrar los cursos por ciclo lectivo si se proporciona
        if ($cicloLectivo) {
            // Filtrar los cursos en base al ciclo lectivo
             $cursos = $cursoRepository->findByCicloLectivo($cicloLectivo);
        } else {
            // Si no se proporciona el ciclo lectivo, obtener todos los cursos
            $cursos = $cursoRepository->findAll();
        }
    
        // Limpiar variables de sesión
        if ($tecId !== null) {
            $session->remove('tecId');
        }
    
        if ($comId !== null) {
            $session->remove('comId');
        }
    
        if ($cursoId !== null) {
            $session->remove('cursoId');
        }
    
        // Renderizar la vista con los resultados filtrados
        return $this->render('vistascursada/index.html.twig', [
            'tecnicaturas' => $tecnicaturaRepository->findAll(),
            'asignaturas' => $asignaturaRepository->findAll(),
            'comisiones' => $comisionRepository->findAll(),
            'cursadas' => $cursadaRepository->findAll(),
            'cursos' => $cursos, // Cursos filtrados
            'cursada_docentes' => $cursadaDocenteRepository->findAll(),
            'tecId' => $tecId,
            'comId' => $comId,
            'cursoId' => $cursoId,
            'cicloLectivo' => $cicloLectivo,
        ]);
    }

    /*
    #[Route('/vistascursada', name: 'app_vistascursada')]
    public function index(CursadaDocenteRepository $cursadaDocenteRepository, CursoRepository $cursoRepository, CursadaRepository $cursadaRepository, ComisionRepository $comisionRepository, TecnicaturaRepository $tecnicaturaRepository, AsignaturaRepository $asignaturaRepository, Request $request): Response
    {
        // Recuperar `tecId` de la sesión esto para cuando estoy cargando asignaturas y que no se pierda tecId
        $session = $request->getSession();
        $tecId = $session->get('tecId', null);
        $comId = $session->get('comId', null);
        $cursoId = $session->get('cursoId', null);

        if ($tecId === null) {
            $tecId = null; 
        } else {
            $session->remove('tecId');
        }

        if ($comId === null) {
            $comId = null; 
        } else {
            $session->remove('comId');
        }

        if ($cursoId === null) {
            $cursod = null; 
        } else {
            $session->remove('cursoId');
        }
    
        return $this->render('vistascursada/index.html.twig', [
            'tecnicaturas' => $tecnicaturaRepository->findAll(),
            'asignaturas' => $asignaturaRepository->findAll(),
            'comisiones' => $comisionRepository->findAll(),
            'cursadas' => $cursadaRepository->findAll(),
            'cursos' => $cursoRepository->findAll(),
            'cursada_docentes' => $cursadaDocenteRepository->findAll(),
            'tecId' => $tecId,
            'comId' => $comId,
            'cursoId' => $cursoId,
        ]);
    }*/

    #[Route('/cursodocente/{curso_id?}', name: 'crear_cursada_docente', methods: ['GET', 'POST'])]
    public function createCursadaDocente(Request $request, CursadaDocenteRepository $cursadaDocenteRepository): Response
    {
        $curso_id = $request->attributes->get('curso_id', null);
    
        // Almacenar `cursoId` en la sesión
        $session = $request->getSession();
        if ($curso_id !== null) {
            $session->set('cursoId', $curso_id);
        }

        $cursoId = $session->get('cursoId', null); 

        $cursadaDocente = new CursadaDocente();
        $form = $this->createForm(CursadaDocenteType::class, $cursadaDocente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cursadaDocenteRepository->save($cursadaDocente, true);

            if ($request->isXmlHttpRequest()) {
                return new JsonResponse([
                    'success' => true,
                    'message' => 'Comision actualizada correctamente.',
                ]);
            }
            // Redirigir a la vista `index` con todos los datos
            return $this->redirectToRoute('app_vistascursada');
        }
        if ($request->isXmlHttpRequest()) {
            return $this->render('vistascursada/create_form_cursadadocente.html.twig', [
                'cursada_docente' => $cursadaDocente,
                'form' => $form->createView(),
                'cursoId' => $cursoId,
            ]);
        }
    
        return $this->renderForm('vistascursada/create_form_cursadadocente.html.twig', [
            'cursada_docente' => $cursadaDocente,
            'form' => $form,
            'cursoId' => $cursoId,
        ]);

       
    }
    
    
    #[Route('/editarcursadadocente/{curso_id}/{cursada_docente_id}', name: 'editar_cursada_docente')]
    public function editarCursadaDocente(Request $request, CursadaDocenteRepository $cursadaDocenteRepository, int $curso_id, int $cursada_docente_id): Response
    {
        // Obtener el objeto CursadaDocente
        $cursadaDocente = $cursadaDocenteRepository->find($cursada_docente_id);
        if (!$cursadaDocente) {
            throw $this->createNotFoundException('CursadaDocente no encontrado');
        }
    
        $form = $this->createForm(CursadaDocenteType::class, $cursadaDocente);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $cursadaDocenteRepository->save($cursadaDocente, true);
    
            if ($request->isXmlHttpRequest()) {
                return new JsonResponse([
                    'success' => true,
                    'message' => 'Cursada Docente actualizada correctamente.',
                ]);
            }
    
            // Redirigir a la vista `index` con todos los datos
            return $this->redirectToRoute('app_vistascursada');
        }
    
        if ($request->isXmlHttpRequest()) {
            return $this->render('vistascursada/edit_cursadadocente.html.twig', [
                'cursadaDocente' => $cursadaDocente,
                'form' => $form->createView(),
                'cursoId' => $curso_id,
            ]);
        }
    
        return $this->renderForm('vistascursada/edit_cursadadocente.html.twig', [
            'cursadaDocente' => $cursadaDocente,
            'form' => $form,
            'cursoId' => $curso_id,
        ]);
    }

    //crear comision
    #[Route('/comisiones/{tecnicatura_id?}', name: 'crear_comision', methods: ['GET', 'POST'])]
    public function createComision(Request $request, ComisionRepository $comisionRepository): Response
    {
        $tecnicatura_id = $request->attributes->get('tecnicatura_id', null);   
        // Almacenar `tecId` en la sesión
        $session = $request->getSession();
        if ($tecnicatura_id !== null) {
            $session->set('tecId', $tecnicatura_id);
        }
        $tecId = $session->get('tecId', null);    
        $comision = new Comision();
        $form = $this->createForm(ComisionType::class, $comision);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comisionRepository->save($comision, true);   
            if ($request->isXmlHttpRequest()) {
                return new JsonResponse([
                    'success' => true,
                    'message' => 'Comision actualizada correctamente.',
                ]);
            }
            // Redirigir a la vista `index` con todos los datos
            return $this->redirectToRoute('app_vistascursada');
        }
        if ($request->isXmlHttpRequest()) {
            return $this->render('vistascursada/create_form.html.twig', [
                'comision' => $comision,
                'form' => $form->createView(),
                'tecId' => $tecId,
            ]);
        }
    
        return $this->renderForm('vistascursada/create_form.html.twig', [
            'comision' => $comision,
            'form' => $form,
            'tecId' => $tecId,
        ]);
    }

templates/vistascursada/create_form.html.twig
Creando Comisión Nueva 

{# templates/vistas/create_form.html.twig #} 

{{ form_start(form, {'attr': {'id': 'form-crea-comision', 'action': path('crear_comision' )}}) }}
        {{ form_row(form.anio, {'label': 'Año'})}} 
        {{ form_row(form.comision, {'label': 'Comisión'})}}
        {{ form_row(form.turno, {'label': 'Turno'}) }}
        {{ form_row(form.tecnicatura, {'label': 'Tecnicatura'})}}
        {{ form_row(form.ciclo_lectivo, {'label': 'Ciclo Lectivo'})}}
       {{ form_row(form.estado, {'label': 'Estado'}) }}


    <button type="submit"class="button">Guardar</button>
{{ form_end(form) }}

templates/vistascursada/create_form2.html.twig
{{ form_start(form, {
    'attr': {'id': 'form-crea-cursada'},
    'action': path('crear_cursada', { 'tecnicatura_id': tecId, 'comision_id': comId })
}) }}
        {{ form_row(form.condicion, {'label': 'Condición'})  }}
        {{ form_row(form.alumno, {'label': 'Alumno'})  }}
        {{ form_row(form.modalidad, {'label': 'Modalidad'})  }}
        {{ form_row(form.nota_id, {'label': 'Nota'})  }}
        {{ form_row(form.curso, {'label': 'Curso'})  }} 
    <button type="submit"class="button">Guardar</button>
{{ form_end(form) }}

templates/vistascursada/create_form_cursadadocente.html.twig
{{ form_start(form, {
    'attr': {'id': 'form-crea-cursadadocente'},
    'action': path('crear_cursada_docente', { 'curso_id': cursoId })
}) }}

        {{ form_row(form.toma, {'label': 'Fecha de Toma'})}}
        {{ form_row(form.cese, {'label': 'Fecha de Cese'})}}
        {{ form_row(form.docente, {'label': 'Docente'})}}
        {{ form_row(form.revista, {'label': 'Situación de Revista'})}}
        {{ form_row(form.licencia, {'label': 'Licencia'})}}
        {{ form_row(form.curso, {'label': 'Curso'})}}
    <button type="submit"class="button">Guardar</button>
{{ form_end(form) }}
 

templates/vistascursada/create_form_curso.html.twig
{{ form_start(form, {
    'attr': {'id': 'form-crea-curso'},
    'action': path('crear_curso', { 'tecnicatura_id': tecId, 'comision_id': comId })
}) }}

        {{ form_row(form.CUPOF, {'label': 'CUPOF'})}}
        {{ form_row(form.asignatura, {'label': 'Asignatura'})}}
        {{ form_row(form.comision, {'label': 'Comisión'})}}
    <button type="submit"class="button">Guardar</button>
{{ form_end(form) }}

templates/vistascursada/edit_cursadadocente.html.twig
{{ form_start(form, {'attr': {'id': 'form-edit-cursada-docente', 'action': path('editar_cursada_docente', {'curso_id': cursoId, 'cursada_docente_id': cursadaDocente.id})}}) }}

{{ form_row(form.toma, {'label': 'Fecha de Toma'}) }}
{{ form_row(form.cese, {'label': 'Fecha de Cese'}) }}
{{ form_row(form.docente, {'label': 'Docente'}) }}
{{ form_row(form.revista, {'label': 'Situación de Revista'}) }}
{{ form_row(form.licencia, {'label': 'Licencia'}) }}
{{ form_row(form.curso, {'label': 'Curso'}) }} 


<button type="submit" id="guarda-modal-edit"class="button">Guardar</button>

{{ form_end(form) }}

templates/vistascursada/edit_form_comision.html.twig
{{ form_start(form, {'attr': {'id': 'form-edit-comision', 'action': path('editar_comision', {'comision_id': comision.id, 'tecnicatura_id': tecId})}}) }}
    {{ form_row(form.anio, {'label': 'Año'})  }} 
    {{ form_row(form.comision, {'label': 'Comisión'}) }}
    {{ form_row(form.turno, {'label': 'Turno'}) }} 
    {{ form_row(form.tecnicatura, {'label': 'Tecnicatura'}) }}
    {{ form_row(form.ciclo_lectivo, {'label': 'Ciclo Lectivo'})}}

    
    <button type="submit" id="guarda-modal-edit"class="button">Guardar</button>

{{ form_end(form) }} 

templates/vistascursada/edit_form_cursada.html.twig
{{ form_start(form, {'attr': {'id': 'form-edit-cursada', 'action': path('editar_cursada', {'cursada_id': cursada.id})}}) }}
        {{ form_row(form.condicion, {'label': 'Condición'}) }}
        {{ form_row(form.alumno, {'label': 'Alumno'}) }}
        {{ form_row(form.modalidad, {'label': 'Modalidad'}) }}
        {{ form_row(form.nota_id, {'label': 'Nota'})  }}
        {{ form_row(form.curso, {'label': 'Curso'}) }} 

    <button type="submit" id="guarda-modal-edit"class="button">Guardar</button>

{{ form_end(form) }} 

templates/vistascursada/edit_form_curso.html.twig
{{ form_start(form, {'attr': {'id': 'form-edit-comision', 'action': path('editar_curso', {'curso_id': curso.id})}}) }}
        
        {{ form_row(form.CUPOF, {'label': 'CUPOF'})}}
        {{ form_row(form.asignatura, {'label': 'Asignatura'})}}
        {{ form_row(form.comision, {'label': 'Comisión'})}}

    <button type="submit" id="guarda-modal-edit"class="button">Guardar</button>

{{ form_end(form) }} 