src/Entity/Instituto.php
<?php

namespace App\Entity;

use App\Repository\InstitutoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InstitutoRepository::class)]
class Instituto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nombre = null;

    #[ORM\Column(length: 50)]
    private ?string $numero = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $url_instituto = null;

    #[ORM\Column(length: 6)]
    private ?string $tipo = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 100)]
    private ?string $calle = null;

    #[ORM\Column(length: 10)]
    private ?string $altura = null;

    #[ORM\Column(length: 15)]
    private ?string $numero_cue = null;

    #[ORM\ManyToOne(inversedBy: 'instituto')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Localidad $localidad = null;

    #[ORM\OneToMany(mappedBy: 'instituto', targetEntity: Telefono::class)]
    private Collection $telefono;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $instituto = null;

    public function __construct()
    {
        $this->telefono = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

 

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getUrlInstituto(): ?string
    {
        return $this->url_instituto;
    }

    public function setUrlInstituto(?string $url_instituto): static
    {
        $this->url_instituto = $url_instituto;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): static
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCalle(): ?string
    {
        return $this->calle;
    }

    public function setCalle(string $calle): static
    {
        $this->calle = $calle;

        return $this;
    }

    public function getAltura(): ?string
    {
        return $this->altura;
    }

    public function setAltura(string $altura): static
    {
        $this->altura = $altura;

        return $this;
    }

    public function getNumeroCue(): ?string
    {
        return $this->numero_cue;
    }

    public function setNumeroCue(string $numero_cue): static
    {
        $this->numero_cue = $numero_cue;

        return $this;
    }

    public function getLocalidad(): ?Localidad
    {
        return $this->localidad;
    }

    public function setLocalidad(?Localidad $localidad): static
    {
        $this->localidad = $localidad;

        return $this;
    }

    /**
     * @return Collection<int, Telefono>
     */
    public function getTelefono(): Collection
    {
        return $this->telefono;
    }

    public function addTelefono(Telefono $telefono): static
    {
        if (!$this->telefono->contains($telefono)) {
            $this->telefono->add($telefono);
            $telefono->setInstituto($this);
        }

        return $this;
    }

    public function removeTelefono(Telefono $telefono): static
    {
        if ($this->telefono->removeElement($telefono)) {
            // set the owning side to null (unless already changed)
            if ($telefono->getInstituto() === $this) {
                $telefono->setInstituto(null);
            }
        }

        return $this;
    }

    public function getInstituto(): ?string
    {
        return $this->instituto;
    }

    public function setInstituto(?string $instituto): static
    {
        $this->instituto = $instituto;

        return $this;
    }
    public function __toString(): string
    {
        return $this->numero ;
    }
}

src/Form/InstitutoType.php
<?php

namespace App\Form;

use App\Entity\Instituto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InstitutoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('numero')
            ->add('url_instituto')
            ->add('tipo')
            ->add('email')
            ->add('calle')
            ->add('altura')
            ->add('numero_cue')
            ->add('instituto')
            ->add('localidad')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Instituto::class,
        ]);
    }
}

src/Controller/InstitutoController.php
<?php

namespace App\Controller;

use App\Entity\Instituto;
use App\Form\InstitutoType;
use App\Repository\InstitutoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/instituto')]
class InstitutoController extends AbstractController
{
    #[Route('/', name: 'app_instituto_index', methods: ['GET'])]
    public function index(InstitutoRepository $institutoRepository): Response
    {
        return $this->render('instituto/index.html.twig', [
            'institutos' => $institutoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_instituto_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InstitutoRepository $institutoRepository): Response
    {
        $instituto = new Instituto();
        $form = $this->createForm(InstitutoType::class, $instituto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $institutoRepository->save($instituto, true);

            return $this->redirectToRoute('app_instituto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('instituto/new.html.twig', [
            'instituto' => $instituto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_instituto_show', methods: ['GET'])]
    public function show(Instituto $instituto): Response
    {
        return $this->render('instituto/show.html.twig', [
            'instituto' => $instituto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_instituto_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Instituto $instituto, InstitutoRepository $institutoRepository): Response
    {
        $form = $this->createForm(InstitutoType::class, $instituto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $institutoRepository->save($instituto, true);

            return $this->redirectToRoute('app_instituto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('instituto/edit.html.twig', [
            'instituto' => $instituto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_instituto_delete', methods: ['POST'])]
    public function delete(Request $request, Instituto $instituto, InstitutoRepository $institutoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$instituto->getId(), $request->request->get('_token'))) {
            $institutoRepository->remove($instituto, true);
        }

        return $this->redirectToRoute('app_instituto_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/instituto/_delete_form.html.twig
<form method="post" action="{{ path('app_instituto_delete', {'id': instituto.id}) }}" onsubmit="return confirm('Confirmar Eliminación');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ instituto.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/instituto/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/instituto/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Instituto{% endblock %}

{% block body %}
    <h1>Editar Instituto</h1>

    {{ include('instituto/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('app_instituto_index') }}">Regresar</a>

    {{ include('instituto/_delete_form.html.twig') }}
{% endblock %}

templates/instituto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Instituto index{% endblock %}

{% block body %}
    <h1>Listado de Institutos</h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Número</th>
                <th>URL del Instituto</th>
                <th>Tipo</th>
                <th>E-Mail</th>
                <th>Calle</th>
                <th>Altura</th>
                <th>Número de CUE</th>
                <th>Instituto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for instituto in institutos %}
            <tr>
                <td>{{ instituto.id }}</td>
                <td>{{ instituto.nombre }}</td>
                <td>{{ instituto.numero }}</td>
                <td>{{ instituto.urlInstituto }}</td>
                <td>{{ instituto.tipo }}</td>
                <td>{{ instituto.email }}</td>
                <td>{{ instituto.calle }}</td>
                <td>{{ instituto.altura }}</td>
                <td>{{ instituto.numeroCue }}</td>
                <td>{{ instituto.instituto }}</td>
                <td>
                    <a href="{{ path('app_instituto_show', {'id': instituto.id}) }}">Mostrar</a>
                    <a href="{{ path('app_instituto_edit', {'id': instituto.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">No se encontraron registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_instituto_new') }}">Crear Nuevo Instituto</a>
{% endblock %}

templates/instituto/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Instituto{% endblock %}

{% block body %}
    <h1>Crear Nuevo Instituto</h1>

    {{ include('instituto/_form.html.twig') }}

    <a href="{{ path('app_instituto_index') }}">Regresar</a>
{% endblock %}

templates/instituto/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Instituto{% endblock %}

{% block body %}
    <h1> Mostrando Institutos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ instituto.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ instituto.nombre }}</td>
            </tr>
            <tr>
                <th>Número</th>
                <td>{{ instituto.numero }}</td>
            </tr>
            <tr>
                <th>URL del Instituto</th>
                <td>{{ instituto.urlInstituto }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ instituto.tipo }}</td>
            </tr>
            <tr>
                <th>E-Mail</th>
                <td>{{ instituto.email }}</td>
            </tr>
            <tr>
                <th>Calle</th>
                <td>{{ instituto.calle }}</td>
            </tr>
            <tr>
                <th>Altura</th>
                <td>{{ instituto.altura }}</td>
            </tr>
            <tr>
                <th>Número de CUE</th>
                <td>{{ instituto.numeroCue }}</td>
            </tr>
            <tr>
                <th>Instituto</th>
                <td>{{ instituto.instituto }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_instituto_index') }}">Regresar</a>

    <a href="{{ path('app_instituto_edit', {'id': instituto.id}) }}">Editar</a>

    {{ include('instituto/_delete_form.html.twig') }}
{% endblock %}